// <auto-generated />
using System;
using DiyetisyenRandevuSistemi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiyetisyenRandevuSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiyetisyenRandevuSistemi.Models.Abonelik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Baslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Bitis")
                        .HasColumnType("datetime2");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<int>("HekimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaketId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaketId");

                    b.HasIndex("UserId");

                    b.HasIndex("HekimId", "Baslangic")
                        .IsUnique();

                    b.ToTable("Randevular", (string)null);
                });

            modelBuilder.Entity("DiyetisyenRandevuSistemi.Models.Diyetisyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uzmanlik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diyetisyenler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adi = "Dyt. Ayşe Yılmaz",
                            Password = "12345",
                            ResimUrl = "/İmages/diyetisyen1.jpg",
                            Username = "ayse",
                            Uzmanlik = "Kilo Kontrolü ve Sporcu Beslenmesi"
                        },
                        new
                        {
                            Id = 2,
                            Adi = "Dyt. Mehmet Can",
                            Password = "12345",
                            Username = "mehmet",
                            Uzmanlik = "Çocuk ve Ergen Beslenmesi"
                        },
                        new
                        {
                            Id = 3,
                            Adi = "Dyt. Selin Koç",
                            Password = "12345",
                            Username = "selin",
                            Uzmanlik = "Hastalıkta Beslenme"
                        },
                        new
                        {
                            Id = 4,
                            Adi = "Dyt. Barış Kaya",
                            Password = "12345",
                            Username = "baris",
                            Uzmanlik = "Gebelik ve Emzirme Dönemi Beslenme"
                        },
                        new
                        {
                            Id = 5,
                            Adi = "Dyt. Elif Güneş",
                            Password = "12345",
                            Username = "elif",
                            Uzmanlik = "Vejetaryen/Vegan Beslenme"
                        });
                });

            modelBuilder.Entity("DiyetisyenRandevuSistemi.Models.HekimCalismaPlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Baslangic")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Bitis")
                        .HasColumnType("time");

                    b.Property<int>("DiyetisyenId")
                        .HasColumnType("int");

                    b.Property<int>("Gun")
                        .HasColumnType("int");

                    b.Property<int>("SlotDakika")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiyetisyenId");

                    b.ToTable("HekimCalismaPlanlari", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1011,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 1,
                            Gun = 1,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1012,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 1,
                            Gun = 2,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1013,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 1,
                            Gun = 3,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1014,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 1,
                            Gun = 4,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1015,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 1,
                            Gun = 5,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1021,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 2,
                            Gun = 1,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1022,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 2,
                            Gun = 2,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1023,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 2,
                            Gun = 3,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1024,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 2,
                            Gun = 4,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1025,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 2,
                            Gun = 5,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1031,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 3,
                            Gun = 1,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1032,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 3,
                            Gun = 2,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1033,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 3,
                            Gun = 3,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1034,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 3,
                            Gun = 4,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1035,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 3,
                            Gun = 5,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1041,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 4,
                            Gun = 1,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1042,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 4,
                            Gun = 2,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1043,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 4,
                            Gun = 3,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1044,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 4,
                            Gun = 4,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1045,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 4,
                            Gun = 5,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1051,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 5,
                            Gun = 1,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1052,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 5,
                            Gun = 2,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1053,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 5,
                            Gun = 3,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1054,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 5,
                            Gun = 4,
                            SlotDakika = 30
                        },
                        new
                        {
                            Id = 1055,
                            Baslangic = new TimeSpan(0, 9, 0, 0, 0),
                            Bitis = new TimeSpan(0, 17, 0, 0, 0),
                            DiyetisyenId = 5,
                            Gun = 5,
                            SlotDakika = 30
                        });
                });

            modelBuilder.Entity("DiyetisyenRandevuSistemi.Models.Paket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int?>("AylikGun")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HaftalikGun")
                        .HasColumnType("int");

                    b.Property<int>("HekimId")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HekimId");

                    b.HasIndex("UserId");

                    b.ToTable("Paketler");
                });

            modelBuilder.Entity("DiyetisyenRandevuSistemi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DiyetisyenRandevuSistemi.Models.Abonelik", b =>
                {
                    b.HasOne("DiyetisyenRandevuSistemi.Models.Diyetisyen", "Hekim")
                        .WithMany("Randevular")
                        .HasForeignKey("HekimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiyetisyenRandevuSistemi.Models.Paket", "Paket")
                        .WithMany("Randevular")
                        .HasForeignKey("PaketId");

                    b.HasOne("DiyetisyenRandevuSistemi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hekim");

                    b.Navigation("Paket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiyetisyenRandevuSistemi.Models.HekimCalismaPlani", b =>
                {
                    b.HasOne("DiyetisyenRandevuSistemi.Models.Diyetisyen", "Diyetisyen")
                        .WithMany("CalismaPlanlari")
                        .HasForeignKey("DiyetisyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diyetisyen");
                });

            modelBuilder.Entity("DiyetisyenRandevuSistemi.Models.Paket", b =>
                {
                    b.HasOne("DiyetisyenRandevuSistemi.Models.Diyetisyen", "Hekim")
                        .WithMany()
                        .HasForeignKey("HekimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiyetisyenRandevuSistemi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hekim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiyetisyenRandevuSistemi.Models.Diyetisyen", b =>
                {
                    b.Navigation("CalismaPlanlari");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("DiyetisyenRandevuSistemi.Models.Paket", b =>
                {
                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
